[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 run.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PORT = "8000"
