services:
  - type: web
    name: ai-career-toolkit-api
    env: python
    rootDir: ./backend
    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "gunicorn -c ../gunicorn.conf.py main:app"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: mysql+pymysql://root:HyxmfTDZYnoyEwgzlGEKVTpTBiBTAMlR@interchange.proxy.rlwy.net:38646/railway
      - key: SECRET_KEY
        value: 368706717ee96c0554530193f834eed6addfe965c1baa361
      - key: DEBUG
        value: False
      - key: APP_NAME
        value: AI Career Toolkit
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
